### ISSUE TITLE
Populate All Vault in the credential dropdown with the list of the vaults and update the name as selected in the credential 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#1270]

**Comment by birtony** [comment]
As discussed, in order to persist the vault selection for entire user session (including when the page is manually reloaded or when the user visits other pages and then comes back to the credentials), we will have to store the selected vault's `id` in the vuex store.

Please, share any concerns regarding this approach @talwinder50 @sudeshrshetty @rolsonquadras
